### ISSUE TITLE
How can I plug your optimiser to Keras?

### ISSUE THREAD

**Issue by haskarb** [harvitronix/neural-network-genetic-algorithm#2]
Can you tell if your optimiser be plugged to Keras?

**Comment by harvitronix** [comment]
I'm not sure what you mean... the optimizer uses Keras to build/train/test the networks. If you want to use it for your own networks built using Keras, you'll need to update the code to do so.

If you're looking for something that can just plug right into Keras as a library, you may want to look at hyperas: https://github.com/maxpumperla/hyperas
