### ISSUE TITLE
Needed a little help.

### ISSUE THREAD

**Issue by umbracide** [harvitronix/neural-network-genetic-algorithm#3]
Hey!

Firstly, I found this NN amazing and this whole repo very informative. But I'm also kind of just starting off with Neural Networks. I didn't know how I could implement it after training it. I don't even know if my NN is being trained or not. When i put the main.py module through my terminal, it just says that its using the TensorFlow backend and then just stops running the code.

I'm running the same modules you are, I just went through them a couple of times to understand what you were doing in the code, but aside from that the code is untouched. I was really hoping you could help me out with this.

Thanks in advanced!

**Comment by harvitronix** [comment]
Hello @umbracide! There are two places where you can see some more useful output. For one, as the program runs, it logs to `log.txt`. So after you start `main.py`, you could `tail -f log.txt` in another terminal to see the output there.

The other thing you can do is change `verbose=0` to `verbose=1` in the `train.py` file in both the `fit()` and `evaluate` functions. This will show you the neural net training progress as it's training.

Hope that helps!
